"""Book-case OOS verification.

Phase 2 of the backtest framework. The book (성승현, 캔들차트 하나로
끝내는 추세추종 투자, 2026) describes specific historical entries +
exits with their realized returns. We re-run our analyzer on the SAME
historical bars and assert that:

  (a) we fire a buy signal within ±N weeks of the book's entry,
  (b) we fire an exit signal within ±N weeks of the book's exit,
  (c) the realized return between our entry/exit is within tolerance
      of the book's reported figure.

These tests are anchored to fixture JSON files (`fixtures/*.json`)
generated by `fetch_fixture.py`. Fixtures are tracked in git so the
test runs deterministically in CI without hitting FDR / Naver.

Cases covered (so far):
  - 035720.KS (카카오)   2019-04 entry → 2021-09 exit, +390% (월봉 쌍봉)
  - 005930.KS (삼성전자) ~5y monthly,   4 entries, 1 small loss
  - 005930.KS (삼성전자) Cup-and-Handle 240MA breakout (주봉)
"""
