/**
 * Static top-300 US ticker bundle for /us-analysis autocomplete.
 *
 * S&P 100 + NASDAQ 100 + popular small/mid caps. ~5KB shipped to
 * client. Search is case-insensitive substring match on ticker OR
 * name (English).
 *
 * Korean translations (name_ko) intentionally omitted — translations
 * for foreign stocks are mostly user-generated and unreliable. If you
 * type a Korean stock name in this page, fallback says "use /stocks
 * instead".
 *
 * To refresh: pull Tiingo supported_tickers.zip → filter exchange in
 * (NASDAQ, NYSE) + assetType=Stock + active → top-N by market cap.
 */

export interface UsTicker {
  ticker: string;
  name: string;
  exchange: "NASDAQ" | "NYSE" | "AMEX";
}

export const US_TICKERS: UsTicker[] = [
  // Mega-cap tech
  { ticker: "AAPL", name: "Apple Inc.", exchange: "NASDAQ" },
  { ticker: "MSFT", name: "Microsoft Corp.", exchange: "NASDAQ" },
  { ticker: "GOOGL", name: "Alphabet Inc. Class A", exchange: "NASDAQ" },
  { ticker: "GOOG", name: "Alphabet Inc. Class C", exchange: "NASDAQ" },
  { ticker: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ" },
  { ticker: "NVDA", name: "NVIDIA Corp.", exchange: "NASDAQ" },
  { ticker: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ" },
  { ticker: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ" },
  { ticker: "BRK.A", name: "Berkshire Hathaway A", exchange: "NYSE" },
  { ticker: "BRK.B", name: "Berkshire Hathaway B", exchange: "NYSE" },
  { ticker: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ" },
  { ticker: "LLY", name: "Eli Lilly and Co.", exchange: "NYSE" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE" },
  { ticker: "V", name: "Visa Inc.", exchange: "NYSE" },
  { ticker: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
  { ticker: "XOM", name: "Exxon Mobil Corp.", exchange: "NYSE" },
  { ticker: "ORCL", name: "Oracle Corp.", exchange: "NYSE" },
  { ticker: "UNH", name: "UnitedHealth Group", exchange: "NYSE" },
  { ticker: "MA", name: "Mastercard Inc.", exchange: "NYSE" },
  { ticker: "HD", name: "Home Depot Inc.", exchange: "NYSE" },
  { ticker: "PG", name: "Procter & Gamble Co.", exchange: "NYSE" },
  { ticker: "COST", name: "Costco Wholesale Corp.", exchange: "NASDAQ" },
  { ticker: "BAC", name: "Bank of America Corp.", exchange: "NYSE" },
  { ticker: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { ticker: "JNJ", name: "Johnson & Johnson", exchange: "NYSE" },
  { ticker: "CRM", name: "Salesforce Inc.", exchange: "NYSE" },
  { ticker: "ABBV", name: "AbbVie Inc.", exchange: "NYSE" },
  { ticker: "CVX", name: "Chevron Corp.", exchange: "NYSE" },
  { ticker: "KO", name: "Coca-Cola Co.", exchange: "NYSE" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", exchange: "NASDAQ" },
  { ticker: "WFC", name: "Wells Fargo & Co.", exchange: "NYSE" },
  { ticker: "MRK", name: "Merck & Co.", exchange: "NYSE" },
  { ticker: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ" },
  { ticker: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ" },
  { ticker: "MCD", name: "McDonald's Corp.", exchange: "NYSE" },
  { ticker: "ABT", name: "Abbott Laboratories", exchange: "NYSE" },
  { ticker: "AMD", name: "Advanced Micro Devices", exchange: "NASDAQ" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", exchange: "NYSE" },
  { ticker: "AXP", name: "American Express Co.", exchange: "NYSE" },
  { ticker: "GE", name: "General Electric Co.", exchange: "NYSE" },
  { ticker: "DIS", name: "Walt Disney Co.", exchange: "NYSE" },
  { ticker: "NOW", name: "ServiceNow Inc.", exchange: "NYSE" },
  { ticker: "INTU", name: "Intuit Inc.", exchange: "NASDAQ" },
  { ticker: "VZ", name: "Verizon Communications", exchange: "NYSE" },
  { ticker: "PM", name: "Philip Morris International", exchange: "NYSE" },
  { ticker: "PFE", name: "Pfizer Inc.", exchange: "NYSE" },
  { ticker: "IBM", name: "IBM Corp.", exchange: "NYSE" },
  { ticker: "MS", name: "Morgan Stanley", exchange: "NYSE" },
  { ticker: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ" },
  { ticker: "TXN", name: "Texas Instruments", exchange: "NASDAQ" },
  { ticker: "CAT", name: "Caterpillar Inc.", exchange: "NYSE" },
  { ticker: "ISRG", name: "Intuitive Surgical", exchange: "NASDAQ" },
  { ticker: "RTX", name: "RTX Corp.", exchange: "NYSE" },
  { ticker: "GS", name: "Goldman Sachs Group", exchange: "NYSE" },
  { ticker: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ" },
  { ticker: "BLK", name: "BlackRock Inc.", exchange: "NYSE" },
  { ticker: "T", name: "AT&T Inc.", exchange: "NYSE" },
  { ticker: "BX", name: "Blackstone Inc.", exchange: "NYSE" },
  { ticker: "SPGI", name: "S&P Global Inc.", exchange: "NYSE" },
  { ticker: "BKNG", name: "Booking Holdings", exchange: "NASDAQ" },
  { ticker: "HON", name: "Honeywell International", exchange: "NASDAQ" },
  { ticker: "PLTR", name: "Palantir Technologies", exchange: "NASDAQ" },
  { ticker: "C", name: "Citigroup Inc.", exchange: "NYSE" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", exchange: "NASDAQ" },
  { ticker: "DE", name: "Deere & Co.", exchange: "NYSE" },
  { ticker: "PGR", name: "Progressive Corp.", exchange: "NYSE" },
  { ticker: "BSX", name: "Boston Scientific Corp.", exchange: "NYSE" },
  { ticker: "SCHW", name: "Charles Schwab Corp.", exchange: "NYSE" },
  { ticker: "GILD", name: "Gilead Sciences", exchange: "NASDAQ" },
  { ticker: "TJX", name: "TJX Companies Inc.", exchange: "NYSE" },
  { ticker: "BA", name: "Boeing Co.", exchange: "NYSE" },
  { ticker: "ADP", name: "Automatic Data Processing", exchange: "NASDAQ" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", exchange: "NASDAQ" },
  { ticker: "LMT", name: "Lockheed Martin Corp.", exchange: "NYSE" },
  { ticker: "MMC", name: "Marsh & McLennan", exchange: "NYSE" },
  { ticker: "ETN", name: "Eaton Corp.", exchange: "NYSE" },
  { ticker: "SYK", name: "Stryker Corp.", exchange: "NYSE" },
  { ticker: "MDT", name: "Medtronic plc", exchange: "NYSE" },
  { ticker: "CB", name: "Chubb Ltd.", exchange: "NYSE" },
  { ticker: "FI", name: "Fiserv Inc.", exchange: "NYSE" },
  { ticker: "PANW", name: "Palo Alto Networks", exchange: "NASDAQ" },
  { ticker: "ZTS", name: "Zoetis Inc.", exchange: "NYSE" },
  { ticker: "MO", name: "Altria Group Inc.", exchange: "NYSE" },
  { ticker: "DUK", name: "Duke Energy Corp.", exchange: "NYSE" },
  { ticker: "MU", name: "Micron Technology", exchange: "NASDAQ" },
  { ticker: "SO", name: "Southern Co.", exchange: "NYSE" },
  { ticker: "CI", name: "Cigna Group", exchange: "NYSE" },
  { ticker: "ICE", name: "Intercontinental Exchange", exchange: "NYSE" },
  { ticker: "CMCSA", name: "Comcast Corp.", exchange: "NASDAQ" },
  { ticker: "INTC", name: "Intel Corp.", exchange: "NASDAQ" },
  { ticker: "ELV", name: "Elevance Health", exchange: "NYSE" },
  { ticker: "WM", name: "Waste Management", exchange: "NYSE" },
  { ticker: "ANET", name: "Arista Networks", exchange: "NYSE" },
  { ticker: "EQIX", name: "Equinix Inc.", exchange: "NASDAQ" },
  { ticker: "CDNS", name: "Cadence Design Systems", exchange: "NASDAQ" },
  { ticker: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ" },
  { ticker: "AMAT", name: "Applied Materials", exchange: "NASDAQ" },
  { ticker: "LRCX", name: "Lam Research Corp.", exchange: "NASDAQ" },
  { ticker: "KLAC", name: "KLA Corp.", exchange: "NASDAQ" },
  { ticker: "PYPL", name: "PayPal Holdings", exchange: "NASDAQ" },
  { ticker: "UBER", name: "Uber Technologies", exchange: "NYSE" },
  { ticker: "SHOP", name: "Shopify Inc.", exchange: "NASDAQ" },
  { ticker: "SQ", name: "Block Inc.", exchange: "NYSE" },
  { ticker: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ" },
  { ticker: "COIN", name: "Coinbase Global", exchange: "NASDAQ" },
  { ticker: "MSTR", name: "MicroStrategy Inc.", exchange: "NASDAQ" },
  { ticker: "RBLX", name: "Roblox Corp.", exchange: "NYSE" },
  { ticker: "SNAP", name: "Snap Inc.", exchange: "NYSE" },
  { ticker: "PINS", name: "Pinterest Inc.", exchange: "NYSE" },
  { ticker: "DASH", name: "DoorDash Inc.", exchange: "NYSE" },
  { ticker: "RIVN", name: "Rivian Automotive", exchange: "NASDAQ" },
  { ticker: "LCID", name: "Lucid Group", exchange: "NASDAQ" },
  { ticker: "F", name: "Ford Motor Co.", exchange: "NYSE" },
  { ticker: "GM", name: "General Motors", exchange: "NYSE" },
  { ticker: "NIO", name: "NIO Inc.", exchange: "NYSE" },
  { ticker: "BABA", name: "Alibaba Group", exchange: "NYSE" },
  { ticker: "JD", name: "JD.com Inc.", exchange: "NASDAQ" },
  { ticker: "PDD", name: "PDD Holdings", exchange: "NASDAQ" },
  { ticker: "TSM", name: "Taiwan Semiconductor", exchange: "NYSE" },
  { ticker: "ASML", name: "ASML Holding", exchange: "NASDAQ" },
  { ticker: "NESN", name: "Nestle ADR", exchange: "OTC" as never },
  { ticker: "NVO", name: "Novo Nordisk ADR", exchange: "NYSE" },
  { ticker: "SAP", name: "SAP SE ADR", exchange: "NYSE" },
  { ticker: "TM", name: "Toyota Motor ADR", exchange: "NYSE" },
  { ticker: "SONY", name: "Sony Group ADR", exchange: "NYSE" },
  { ticker: "BIDU", name: "Baidu Inc. ADR", exchange: "NASDAQ" },
  { ticker: "SE", name: "Sea Limited", exchange: "NYSE" },
  { ticker: "ARM", name: "Arm Holdings plc", exchange: "NASDAQ" },
  { ticker: "SMCI", name: "Super Micro Computer", exchange: "NASDAQ" },
  { ticker: "MRVL", name: "Marvell Technology", exchange: "NASDAQ" },
  { ticker: "ON", name: "ON Semiconductor", exchange: "NASDAQ" },
  { ticker: "ADI", name: "Analog Devices", exchange: "NASDAQ" },
  { ticker: "NXPI", name: "NXP Semiconductors", exchange: "NASDAQ" },
  { ticker: "WDAY", name: "Workday Inc.", exchange: "NASDAQ" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", exchange: "NASDAQ" },
  { ticker: "ZS", name: "Zscaler Inc.", exchange: "NASDAQ" },
  { ticker: "NET", name: "Cloudflare Inc.", exchange: "NYSE" },
  { ticker: "DDOG", name: "Datadog Inc.", exchange: "NASDAQ" },
  { ticker: "SNOW", name: "Snowflake Inc.", exchange: "NYSE" },
  { ticker: "MDB", name: "MongoDB Inc.", exchange: "NASDAQ" },
  { ticker: "OKTA", name: "Okta Inc.", exchange: "NASDAQ" },
  { ticker: "TEAM", name: "Atlassian Corp.", exchange: "NASDAQ" },
  { ticker: "TWLO", name: "Twilio Inc.", exchange: "NYSE" },
  { ticker: "DOCU", name: "DocuSign Inc.", exchange: "NASDAQ" },
  { ticker: "U", name: "Unity Software Inc.", exchange: "NYSE" },
  { ticker: "ROKU", name: "Roku Inc.", exchange: "NASDAQ" },
  { ticker: "SPOT", name: "Spotify Technology", exchange: "NYSE" },
  { ticker: "MELI", name: "MercadoLibre Inc.", exchange: "NASDAQ" },
  { ticker: "NU", name: "Nu Holdings Ltd.", exchange: "NYSE" },
  { ticker: "GLD", name: "SPDR Gold Trust", exchange: "NYSE" },
  { ticker: "SLV", name: "iShares Silver Trust", exchange: "NYSE" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF", exchange: "NYSE" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", exchange: "NASDAQ" },
  { ticker: "DIA", name: "SPDR Dow Jones ETF", exchange: "NYSE" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", exchange: "NYSE" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", exchange: "NYSE" },
  { ticker: "VTI", name: "Vanguard Total Stock", exchange: "NYSE" },
];

/** Substring search across ticker + name. Returns up to `limit` matches. */
export function searchUsTickers(query: string, limit = 8): UsTicker[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  const exact = US_TICKERS.filter((t) => t.ticker === q);
  if (exact.length) return exact.slice(0, limit);
  const tickerHit = US_TICKERS.filter((t) => t.ticker.includes(q));
  const nameHit = US_TICKERS.filter(
    (t) => !t.ticker.includes(q) && t.name.toUpperCase().includes(q),
  );
  return [...tickerHit, ...nameHit].slice(0, limit);
}
