/**
 * Shared helper for Vercel Cron → GitHub Actions workflow_dispatch.
 *
 * Why: 2026-05-22 the cron split into two independent flows
 * (daily-data.yml + weekly-scan.yml) per book-spirit reorganization.
 * The dispatch logic — Bearer-token auth + REST call to GitHub —
 * is identical across both routes. Centralizing avoids drift between
 * copy-pasted implementations.
 *
 * Flow:
 *   Vercel Cron (vercel.json) → GET /api/cron/<workflow>
 *     with Authorization: Bearer ${CRON_SECRET}
 *   → dispatchWorkflow("file.yml") → GitHub REST API
 *   → workflow runs on main.
 *
 * Auth: Vercel attaches the bearer automatically — no manual setup
 * beyond enabling Cron. CRON_SECRET is generated by Vercel per
 * project.
 */
import { NextResponse } from "next/server";

const OWNER = "jungrok5";
const REPO = "thesauros";

export function verifyCronAuth(req: Request): NextResponse | null {
  const auth = req.headers.get("authorization") ?? "";
  const expected = `Bearer ${process.env.CRON_SECRET ?? ""}`;
  if (!process.env.CRON_SECRET || auth !== expected) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }
  return null;
}

export async function dispatchWorkflow(
  workflowFile: string,
): Promise<NextResponse> {
  const token = process.env.GITHUB_DISPATCH_TOKEN;
  if (!token) {
    return NextResponse.json(
      { error: "GITHUB_DISPATCH_TOKEN not configured" },
      { status: 500 },
    );
  }
  const url =
    `https://api.github.com/repos/${OWNER}/${REPO}` +
    `/actions/workflows/${workflowFile}/dispatches`;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ ref: "main" }),
    });
    if (res.status !== 204) {
      const text = await res.text().catch(() => "");
      return NextResponse.json(
        {
          error: "github dispatch unexpected status",
          status: res.status,
          detail: text.slice(0, 300),
        },
        { status: 502 },
      );
    }
    return NextResponse.json({
      ok: true,
      dispatched_at: new Date().toISOString(),
      workflow: workflowFile,
    });
  } catch (e) {
    return NextResponse.json(
      { error: "dispatch failed", detail: String(e) },
      { status: 502 },
    );
  }
}
